schema_version: 1

geometry:
  nx: 16
  ny: 16
  dx: 0.0049
  dy: 0.0049
  origin: [0.0, 0.0, 0.0]
  normal: [1.0, 0.0, 0.0]
  x_axis_hint: [0.0, 1.0, 0.0]

control:
  mode: focus
  params:
    focal_point: [0.0, 0.0, 0.8]

quantization:
  bits: 0

pattern_mode:
  normalization: peak_0db
  rx_sweep_deg:
    start: -90.0
    stop: 90.0
    step: 1.0

experiment:
  frequency_hz: 28000000000
  tx_incident_angle_deg: -30.0
  tx_distance_m: 0.4
  rx_distance_m: 2.0
  tx_gain_dbi: 15.0
  rx_gain_dbi: 22.0
  tx_power_dbm: 28.0
  reflection_coeff: 0.84

output:
  base_dir: outputs
